# Generated by Django 4.0.5 on 2022-06-29 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitola', models.CharField(max_length=50)),
                ('corrente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Conexoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conex', models.CharField(max_length=50)),
                ('k', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LeadAvancada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('desnivel', models.IntegerField()),
                ('vazao', models.IntegerField()),
                ('potencia', models.IntegerField()),
                ('mchs', models.IntegerField()),
                ('dist_hidr', models.IntegerField()),
                ('dist_eletr', models.IntegerField()),
                ('modelo', models.CharField(max_length=50)),
                ('tipo_cabo', models.CharField(max_length=50)),
            ],
        ),
    ]
