# Generated by Django 4.0.5 on 2022-06-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avancada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadavancada',
            name='concessionaria',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadavancada',
            name='cpf_cnpj',
            field=models.CharField(default=0, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadavancada',
            name='email',
            field=models.EmailField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadavancada',
            name='telefone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
