# Generated by Django 4.0.5 on 2022-06-29 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadBasica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf_cnpj', models.CharField(max_length=17)),
                ('concessionaria', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('desnivel', models.IntegerField()),
                ('vazao', models.IntegerField()),
                ('modelo', models.CharField(max_length=20)),
                ('potencia', models.IntegerField()),
                ('mchs', models.IntegerField()),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
