# Generated by Django 4.0.5 on 2022-07-06 00:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadBasicaInfoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf_cnpj', models.CharField(max_length=17)),
                ('concessionaria', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='leadbasica',
            name='concessionaria',
        ),
        migrations.RemoveField(
            model_name='leadbasica',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='leadbasica',
            name='data',
        ),
        migrations.RemoveField(
            model_name='leadbasica',
            name='email',
        ),
        migrations.RemoveField(
            model_name='leadbasica',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='leadbasica',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basica.leadbasicainfopessoal'),
        ),
    ]
