# Generated by Django 4.0.5 on 2022-07-06 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basica', '0002_leadbasicainfopessoal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadbasica',
            name='concessionaria',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadbasica',
            name='cpf_cnpj',
            field=models.CharField(default=0, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadbasica',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='leadbasica',
            name='email',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadbasica',
            name='telefone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadbasica',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='LeadBasicaInfoPessoal',
        ),
    ]
