# Generated by Django 4.0.5 on 2022-07-11 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basica', '0004_remove_leadbasica_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitola', models.CharField(max_length=50)),
                ('corrente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Conexoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conex', models.CharField(max_length=50)),
                ('k', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LeadAvancada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=17)),
                ('concessionaria', models.CharField(blank=True, max_length=50)),
                ('desnivel', models.IntegerField()),
                ('vazao', models.IntegerField()),
                ('potencia', models.IntegerField()),
                ('mchs', models.IntegerField()),
                ('dist_hidr', models.IntegerField()),
                ('dist_eletr', models.IntegerField()),
                ('modelo', models.CharField(max_length=50)),
                ('tipo_cabo', models.CharField(max_length=50)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='leadbasica',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
