# Generated by Django 4.0.5 on 2022-07-11 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basica', '0005_bitola_conexoe_leadavancada_alter_leadbasica_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bitola',
        ),
        migrations.RemoveField(
            model_name='leadavancada',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='leadbasica',
            name='cpf_cnpj',
        ),
        migrations.AddField(
            model_name='leadbasica',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
